name: Build LLVM Clang & Auto Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Memberikan izin ke token GitHub untuk menulis dan membuat Release baru
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Free Disk Space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y bc binutils-dev bison build-essential ca-certificates \
          ccache clang cmake curl file flex git libelf-dev libssl-dev lld make \
          ninja-build pkg-config python3-dev texinfo u-boot-tools xz-utils zlib1g-dev

    - name: Clone tc-build & Run Build
      run: |
        git clone https://github.com/ClangBuiltLinux/tc-build && cd tc-build
        
        # Jalankan build dengan pembatasan Link Jobs agar tidak crash RAM
        ./build-llvm.py \
          --defines LLVM_PARALLEL_COMPILE_JOBS="$(nproc --all)" LLVM_PARALLEL_LINK_JOBS="1" CMAKE_C_FLAGS=-O2 CMAKE_CXX_FLAGS=-O2 \
          --build-type="Release" \
          --multicall \
          --quiet-cmake \
          --install-folder "clang-23" \
          --shallow-clone \
          --targets ARM AArch64 X86 \
          --ref "main" \
          --vendor-string "Royan"
          
        ./build-binutils.py --targets arm aarch64 x86_64

    - name: Compress Toolchain
      run: |
        # Mengompres folder hasil build menjadi format .tar.xz yang sangat padat
        tar -cJf clang-23-built.tar.xz -C tc-build clang-23

    - name: Generate Release Tag & Name
      id: tag
      run: |
        # Membuat penanda tanggal otomatis agar nama rilis unik
        echo "release_tag=clang-23-$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        name: Clang 23 Toolchain (Royan)
        body: |
          Kompilasi LLVM Clang 23 sukses dibuat secara otomatis.
          - **Vendor String**: Royan
          - **Targets**: ARM, AArch64, X86
          - **Type**: Release (Compressed)
        draft: false
        prerelease: false
        files: clang-23-built.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
